### ISSUE TITLE
images not dumped to sub directories

### ISSUE THREAD

**Issue by lampuiho** [WikiTeam/wikiteam#176]
Cellar Bugworm.png  http://img2.wikia.nocookie.net/__cb20110926111515/xenoblade/images/3/3d/Cellar_Bugworm.png  Michael Clark
Cellar bugworm.png  http://img2.wikia.nocookie.net/__cb20140317003937/xenoblade/images/b/bd/Cellar_bugworm.png  Bg123

It just overwrites the same image which is annoying.

**Comment by Moredread** [comment]
I hit this issue a decade later, on a standard wikimedia install, because I needed to do a wiki dump without a linux box available. Also windows produces CRLF in output files.

If Windows or case sensitive filesystems are not supported/untested, atleast a warning would be helpful, that overwriting of an existing file occurred.
