### ISSUE TITLE
dumpgenerator.py - script unusable because of unknown dependencies (kitchen module)

### ISSUE THREAD

**Issue by Sperber03** [WikiTeam/wikiteam#275]
If you start the dumpgenerator.py it ends in an error "print: install kitchen module" . Unfortunal noone knows where to find that kitchen module, what it´s for or whom to ask. The irc-channel on EFNet isn´t existing anymore, the mailing list seems dead and abandond also. 

Is there # **anyone** around here who can **help** with this?

**Comment by nemobis** [comment]
Thanks for using WikiTeam. The module can be installed like any other 
module: https://docs.python.org/2/installing/index.html#installing-index

Try pip install kitchen, or apt-get install python-kitchen, or dnf 
install python-kitchen, and so on. Things may be harder on undeveloped 
OS like Windows.

P.s.: The IRC channel still exists, what makes you think the contrary?

**Comment by nemobis** [comment]
I'm afraid I have to close this issue because there is no way to "fix" it: dumpgenerator.py requires a minimum of command line abilities (and is harder to use on Windows), we are painfully aware of it. We always try to simplify things when we have a chance, also by reducing the dependencies.

>  P.s.: The IRC channel still exists, what makes you think the contrary?

Apparently the user tried to join the channel on FreeNode, while it's on EFNet.
