### ISSUE TITLE
can't download Coursera wiki

### ISSUE THREAD

**Issue by racemus** [WikiTeam/wikiteam#277]
Hi.

I'm trying to download Coursera wiki with next command line:
$ python dumpgenerator.py --user MYLOGIN --pass MYPASSWORD --cookies=cookies.txt --index=https://share.coursera.org/wiki/index.php --xml --images

I generate cookies.txt with cookies.txt Chrome browser extension.
It's not working. What's wrong?

**Comment by nemobis** [comment]
Does it generate the list of titles? Have you tried passing 
--api=https://share.coursera.org/wiki/api.php ?

**Comment by nemobis** [comment]
Looks like it's too late, the wiki doesn't exist any more. Or does it?

The last time I tried several cookies.txt extensions, none really worked well. So it would take some verification of the file first.

We have some issues open about login-only wikis, the problem here was probably one of those:
https://github.com/WikiTeam/wikiteam/issues/28
https://github.com/WikiTeam/wikiteam/issues/71
https://github.com/WikiTeam/wikiteam/issues/80
https://github.com/WikiTeam/wikiteam/issues/304
