### ISSUE TITLE
Function to download the missing pages

### ISSUE THREAD

**Issue by Analyst1996** [WikiTeam/wikiteam#281]
When downloading large wikias, some pages go missing. Can someone add a function to only download the pages that are missing from the dump?

**Comment by nemobis** [comment]
The missing pages fail for a reason, i.e. insufficient RAM. The solution 
is not retrying, but using a different method (e.g. API export, for 
which there is an open PR). So I don't think this request makes sense, 
though we could output a list of failed titles so that one can at least 
use Special:Export in the browser.

**Comment by Analyst1996** [comment]
Sorry.  I am new to using the wikiteam software. About the Ram shortage, could you elaborate a bit? Also is there another way to see which pages failed?

**Comment by Analyst1996** [comment]
Sorry.  I am new to using the wikiteam software. About the Ram shortage, could you elaborate a bit? Also is there another way to see which pages failed?

**Comment by Analyst1996** [comment]
nemobis If i add a delay will that decrease server load and the pages won't miss??

**Comment by nemobis** [comment]
Closing in favor of  the other issue which asks for a list.
