### ISSUE TITLE
Index.php not index.php

### ISSUE THREAD

**Issue by WAUthethird** [WikiTeam/wikiteam#325]
Hey, trying to backup a wiki that for some reason has capitalized their index.php page as "Index.php". The software returns:

```
Looks like the page called Index.php, not index.php itself
Error in index.php.
Please, provide a correct path to index.php or use --xmlrevisions. Terminating.
```
It does not have a valid api.php. How would I back this up?

**Comment by nemobis** [comment]
William Unsworth, 30/08/2018 04:50:
> Hey, trying to backup a wiki that for some reason has capitalized their 
> index.php page as "Index.php". The software returns:

Can you please provide the URL to this index.php. Usually when I see 
this error it's because the URL is redirected to the *article* 
[[Index.php]] which doesn't exist. In some cases, the short 
URLs/webserver configuration is so broken that it's impossible to do 
anything.

If the sysadmin really renamed the *file* index.php to Index.php, then I 
guess replacing all instances with:

sed -i 's/index.php/Index.php/g' dumpgenerator.py

would achieve the expected result. This seems odd though. :)

**Comment by WAUthethird** [comment]
The url is [http://editthis.info/create_your_own_story/index.php](http://editthis.info/create_your_own_story/index.php). It's been categorized as a junk page, for some reason.

**Comment by WAUthethird** [comment]
Tried a few other things, still doesn't work. Any suggestions?

**Comment by nemobis** [comment]
William Unsworth, 01/09/2018 21:36:
> Tried a few other things, still doesn't work. Any suggestions?

Please share the URL of this wiki.

**Comment by WAUthethird** [comment]
I did.

Above:
`The url is http://editthis.info/create_your_own_story/index.php. It's been categorized as a junk page, for some reason.`

**Comment by nemobis** [comment]
Please see <https://www.archiveteam.org/index.php?title=EditThis> on how 
to archive EditThis wikis.
