### ISSUE TITLE
Wikiteam does not run on Windows

### ISSUE THREAD

**Issue by Wikiteam-on-Windows** [WikiTeam/wikiteam#341]
The [Tutorial](https://github.com/WikiTeam/wikiteam/wiki/Tutorial) which is linked from the front page of Wikiteam on Github says this:
> The dump generator will need to be run from a DOS or GNU/Linux command-line. If you encounter issues with missing dependencies, follow [https://github.com/WikiTeam/wikiteam/issues/252 this help guide].

That guide definitely does not do anything to help with problems running on Windows, Wikiteam definitely does NOT at all on Windows currently despite the front page suggesting you can use a DOS command line (most people using Windows currently won't even have DOS the thing to look for to run is called "[Command Prompt](https://en.wikipedia.org/wiki/Cmd.exe)" (can shift+rightclick a folder but it's better to, and avoids most problems with folder permissions such as how python installs to the protected program files folder, to instead open cmd.exe with a right click then click "run as Administrator" and use cd .. to go back up a folder, cd to change to a directory, or dir to list folder contents like LS on linux -- this is mainly stuff to go into the new tutorial if it ever works again)

Reasons it doesn't work are apparently 2 different reasons:

Wikiteam does not work with the latest python v3.73 (which otherwise seems very integrated into Windows, with PIP working):
![wikiteam-error](https://user-images.githubusercontent.com/51112287/58748310-8be7bd00-846e-11e9-9f27-ed2fac547f44.png)

But it's out of the frying pan into the fire with trying python v2.7 because that doesn't have/support PIP on Windows it seems :(
![wikiteam-for-windows-error](https://user-images.githubusercontent.com/51112287/58748317-aae64f00-846e-11e9-8df9-5899bfc42eca.png)

I wrote https://github.com/WikiTeam/wikiteam/wiki/Tutorial#Running_Wikiteam_on_Windows_using_VirtualBox to try help people but thought I should report it too :)

Purity of code is a good cause and all, Windows 10 is spyware, agreed: https://gist.github.com/xvitaly/eafa75ed2cb79b3bd4e9 (Windows 7 can only barely be salvaged per that and even then in 2020 they're going to stop giving security updates so swapping to something easy to start with like Linux Mint or Ubuntu is probably the best choice for everyone), no Microsoft apologist stuff here they turned down a very dark path that made sites like AskWoody quite popular, BUT when the goal is to save everything, pragmatism is called for, making a bigger effort to reach out to people that aren't coders or linux users is the only way to fight the tide ([WikiApiary's "DUMPME"/"Websites/WikiTeam/Unarchived wikis" page](https://wikiapiary.com/wiki/DUMPME) has an IMMENSE backlog): https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers

(there's also some people that are simply never learning how to use a computer because a phone is "good enough" and the tiny screen space and slow Words Per Minute allowed by a phone encourages people to consume content from corporations making stuff on computers whilst making less new things themselves, but there's always [Ubuntu Touch](http://archive.today/2019.04.28-184250/https://en.wikipedia.org/wiki/Template:Mobile_operating_systems) if adoption was bigger I guess, or [Python-Android ports](http://archive.today/2019.06.01-131554/https://stackoverflow.com/questions/101754/is-there-a-way-to-run-python-on-android) which would bring in a lot more people and avenues of phone company bandwidth too)

**Comment by WAUthethird** [comment]
That's odd, I've been able to get it working just fine with the latest Py2 on Windows 10, also installed all the needed and optional modules with pip as well.

**Comment by Wikiteam-on-Windows** [comment]
Should've mentioned when I say Windows I mean Windows 7 as that's the only safe-ish version to use, and only when turning off automatic updates and only not installing the spyware updates they try to push to add in Windows 10's "telemetry": https://gist.github.com/xvitaly/eafa75ed2cb79b3bd4e9

**Comment by WAUthethird** [comment]
Also, I use Anaconda on Windows 10 to run the scripts with Python 2 without messing up my PATH's python3 installation.

It's not impossible to run.

**Comment by WAUthethird** [comment]
I recommend a closure of this issue. The title is not accurate, and a pull request has already been made to add Python 3 support.

**Comment by Codingale** [comment]
Can't Reproduce; Tested:

- Windows 7 Service Pack 1 (6.1.7601)

-  Windows 10 1809

I agree Microsoft is overdoing the tracking, mainly because they laid off the QA team and outsourced it to users, is that share going down in percentage; yes but for Web Users (aka people who aren't contributing to the project / dump scene [likely]) 

I wholeheartedly disagree with saying it's broken because they didn't install it correctly is just plain ignorant, additionally they make unfounded, and uncited arguments that are irrelevant to the issue (as I am also doing by making a comment about it)

I'm honestly just going to break down what I can here:
> does NOT at all on Windows

It does, I confirmed it by dumping 2 Wikis, both on Windows 10, and 7. Are you sure you're running Python 3 and not 2? It seems like it's having issues with the [print syntax](https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-print-function) which changed between those versions.

> most people using Windows currently won't even have DOS the thing to look for

I admit the terminology is wrong, I believe it was meant to be "Terminal" meaning Command Prompt / Power Shell / Bash etc. 

>  cd .. to go back up a folder, cd to change to a directory, or dir to list folder contents like LS on linux -- this is mainly stuff to go into the new tutorial if it ever works again)

I feel like there's a minimum learning curve for this, to install Python, get it setup correctly, and even clone / download the repo you'd probably be lost before you get to basic shell commands. 

Don't get me wrong, nothing with educating them but it could be outside of the scope of the project IMO.

>Purity of code is a good cause and all, Windows 10 is spyware, agreed:

What? Purity of code? Yeah Windows 10 has issues with Telemerty but if you look at the data being sent and not the fear-mongering you'll see mostly mundane things like Crash Dumps, and BSOD logs being sent with device health updates and battery charge estimations, though a few things are bad not all of it is terrible.

Honestly you should give it a try, maybe even install the Linux Subsystem and review it yourself. I use Spybot's Anti-Beacon (Used to use their S&D Software for a long time before that)

> in 2020 they're going to stop giving security updates [to Windows 7]

Yeah old versions stop being Updated, look at how long Vista lasted compared to 7. It's kind of expected, less OSes to maintain the less stress on serious exploits needing patched across various platforms and fewer Team Members needed to support a 10 year old OS.

> swapping to something easy to start with like Linux Mint or Ubuntu is probably the best choice for everyone

Yeah Grandma, this is Linux, no no, not Linus, well, there is a Linux called Linus, but that's another story. Here's how you use Facebook, you need to open your KDE's menu, and use Iceweasel.

But really, not everyone should learn to use Another OS if they're comfortable. Fimiliarity is good, and support for legacy is important. As of speaking at least half of my programs I use daily can't be ran on Linux using Wine or an equivalent. Don't get me wrong, I love Linux (it's why I have the Subsystem installed on my Windows 10 Box) but it's not for everyone, I mean I've met and been "that guy" who suggests Linux to people.

>  BUT when the goal is to save everything, pragmatism is called for, making a bigger effort to reach out to people that aren't coders or linux users is the only way to fight the tide

I'm confused if you wanted people to swap to Linux or not... But I really doubt they're targeting coders. I'm using it to keep a few game Wikis downloaded for offline use, not coding.

I don't think the overall goal is the same for every user, if you're down for saving everything that ever was go for it. Deploy it on a VPS and download all the Wiki's but I really doubt that's what the project is trying to get. Archival is useful, and important, but I think you need to evaluate your mindset a bit and make sure your priorities are in the right spot. Like, most people who find this are simply trying to export a dead wiki into a new one, or even just save some obscure / removed 

>[...]WikiApiary's "DUMPME"/"Websites/WikiTeam/Unarchived wikis" page has an IMMENSE backlog): https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers

I see why you want to get into this, don't get me wrong helping them is great and very kind of you. But most people won't get into it, and the Desktop OS is prominently windows, most users are using Windows and the project works if configured correctly, or ran on the Linux sub-system if you like.

>(there's also some people that are simply never learning how to use a computer because a phone is "good enough"

I.. what? Again you've strayed off topic and seemingly forgot that phones are miniature computers; and if all you do is check the weather, read news, why would you need another big expense?

> [Phones have a] tiny screen space and slow Words Per Minute

There are [recent studies proving otherwise.](https://userinterfaces.aalto.fi/typing37k/) and that most typists are only marginally slower, with some being much faster thanks to features such as auto correct and auto punctuation. While the "tiny screen space" is known, it's not as much as an issues as modern content can scale to the display size and has accessibility those who need it.

> encourages people to consume content from corporations

What? Is this a conspiracy theory? Tiny screens make people read from Big Media? I'm really curious as to where you get this information, and if it's accurate. Additionally, most content in general was always made by a form of company or state funded program. The wealth of information we have accessible is unparalleled.

>corporations [are] making stuff on computers whilst [other people are] making less new things

I don't think you've looked at Social Media and saw the flurry of Art in various forms like Music, Comedy Sketches, and journalism.

Just because desktops and laptops exist doesn't mean people create less, I know so many people who now continue to work from their phones while away from computer in many many ways.

I'm going to stop here as I feel like I've touched as much as I felt like after being up for over 24 hours, and finally finding a way to dump the Wikis I wanted to last week. I hope whoever is running that account reads this and understands, I'm not saying you don't have valid points, but consider the world in a wider prospective and understand not everything is as it seems my dude. Welcome to the internet.

**Comment by Codingale** [comment]
I think the account (Wikiteam-on-Windows) is a new user (Account created in May) whom seems to be impersonating an official Origination member / Contributor despite not being listed like @emijrp etc

They've edited the guide (perhaps deconstructively) and likely mislead people on Windows into thinking this can't be made to work on Windows 7 or 10. 

Also I think it's a version issue, I.E. wrong path due to the print statement in 2.7 being made into a function:
https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-print-function

**Comment by nemobis** [comment]
Thank you both, closing.
