### ISSUE TITLE
update previous dump with new content?

### ISSUE THREAD

**Issue by silverhikari** [WikiTeam/wikiteam#415]
i am wondering if there is a way to update a older dump with the newer content and images from the wiki without having to do a new dump?

**Comment by nemobis** [comment]
Il 26/11/21 03:42, Ethan Kerrick ha scritto:
> i am wondering if there is a way to update a older dump with the newer content and images from the wiki without having to do a new dump?

No, there isn't. This is impossible because it would require knowing 
about all changes and deletions in the timeframe, but the recentchanges 
table is limited in time. If you need incremental dumps, contact the 
wiki sysadmin so that they're produced server-side.
