### ISSUE TITLE
How to use a copied wiki?

### ISSUE THREAD

**Issue by pbz134** [WikiTeam/wikiteam#487]
Hello,

I have just successfully copied a wiki including images (https://touhou-mystias-izakaya.fandom.com), and now have an "images" folder, xml file and index.html file. Opening the html file displays the home page without any styling.

What can I do with these files now? Is there any way to browse my offline copy with images and styling, exactly how it looks on the original website?

Thanks!
![1111](https://github.com/user-attachments/assets/e5ce5aa5-6a5e-451b-83d4-1837515db136)

**Comment by nemobis** [comment]
Il 21/12/24 21:45, pbz134 ha scritto:
> What can I do with these files now? Is there any way to browse my offline copy with images and styling, exactly how it looks on the original website?

XML dumps are mostly useful if you set up a new wiki into which to 
import them. There is documentation for the importing part:
https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps

Replicating a Wikia wiki is probably going to be challenging because 
there are many extensions involved, but it should be possible as it's 
almost all FLOSS. You may be able to find help by asking people who have 
migrated a wiki from Wikia to elsewhere.

If you're not planning to run a fork of the wiki and you just want to 
read the wiki, starting from the XML may be overkill.

**Comment by nemobis** [comment]
Let me know if you don't know where to start, or just email [mediawiki-l](https://lists.wikimedia.org/hyperkitty/list/mediawiki-l@lists.wikimedia.org/) to ask.
