### ISSUE TITLE
launcher.py: set a size limit

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#87]
_From [nemow...@gmail.com](https://code.google.com/u/101255742639286016490/) on January 28, 2014 16:05:36_

Sometimes I wish I could tell launcher.py to skip a wiki if it turns out to have more than, say, 500k pages. That would mean adding an optional argument which triggers a call to the API stats or to Special:Statistics?action=raw before launching dumpgenerator.

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=87_

**Comment by nemobis** [comment]
Nevermind, it's easier to just kill and remove from the list. However it would be nice to add a marker to a directory, or something else, so that if a launcher.py session for a list of APIs gets stuck on a wiki, the next run doesn't also get stuck on the same. That's the most time consuming problem right now.
